name: Deploy to EC2 Servers

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        server: [1, 2, 3, 4, 5, 6] # Definir las instancias como una matriz de números
        host: [HOST1_DNS, HOST2_DNS, HOST3_DNS, HOST4_DNS, HOST5_DNS, HOST6_DNS]

    steps:
      # Paso 1: Configuración de secretos
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # Paso 2: Desplegar los archivos directamente en el directorio /var/www/html de las instancias EC2
      - name: Deploy to Apache Server ${{ matrix.server }}
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ matrix.host}} # Usando el secret dinámico para cada servidor
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: /var/www/html # Desplegar directamente en el directorio Apache

      # Paso 3: Instalar Apache y configurar permisos en las instancias EC2
      - name: Configure Apache and Permissions for Server ${{ matrix.server }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ matrix.host }} # Usar el secret dinámico para la IP/DNS
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Actualizar el sistema y asegurarse de que Apache esté instalado
            sudo apt-get update
            sudo apt-get install -y apache2 php libapache2-mod-php

            # Habilitar y arrancar Apache
            sudo systemctl enable apache2
            sudo systemctl start apache2

            # Cambiar permisos del directorio de Apache para asegurarse de que Apache pueda acceder a los archivos
            sudo chown -R www-data:www-data /var/www/html
            sudo chmod -R 755 /var/www/html

            # Reiniciar Apache para aplicar los cambios
            sudo systemctl restart apache2
